//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities1 : DbContext
    {
        private static DiplomEntities1 _context;
        public DiplomEntities1()
            : base("name=DiplomEntities1")
        {
        }
        public static DiplomEntities1 GetContext()
        {
            if (_context == null)
                _context = new DiplomEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableCommand> TableCommand { get; set; }
        public virtual DbSet<TableUrl> TableUrl { get; set; }
    }
}
