//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCommand
    {
        public int IdCommand { get; set; }
        public string Command { get; set; }
        public int IdUrl { get; set; }
    
        public virtual TableUrl TableUrl { get; set; }
    }
}
